combine_control_expr = false
wrap_comments = true
comment_width = 120
force_explicit_abi = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
max_width = 120
merge_derives = true
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 1
tab_spaces = 4
unstable_features = true
use_try_shorthand = true